info:
  contact: {}
paths:
  /GetSubmitList:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: problem_id
        in: query
        name: problem_id
        type: string
      - description: user_id
        in: query
        name: user_id
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 提交列表
      tags:
      - 公共方法
  /Login:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        type: string
      - description: password
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 登录
      tags:
      - 公共方法
  /Problem:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: category_identity
        in: query
        name: category_identity
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 问题列表
      tags:
      - 公共方法
  /Register:
    post:
      parameters:
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      - description: phone
        in: formData
        name: phone
        required: true
        type: string
      - description: mail
        in: formData
        name: mail
        required: true
        type: string
      - description: code
        in: formData
        name: code
        required: true
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 用户注册
      tags:
      - 公共方法
  /SendCode:
    post:
      parameters:
      - description: Email
        in: formData
        name: Email
        required: true
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 发送验证码
      tags:
      - 公共方法
  /UserRank:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: string
      - description: size
        in: query
        name: size
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 用户排行表
      tags:
      - 公共方法
swagger: "2.0"
