info:
  contact: {}
paths:
  /GetProblemList:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: category_id
        in: query
        name: category_id
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 问题列表
      tags:
      - 公共方法
  /GetSubmitList:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: problem_id
        in: query
        name: problem_id
        type: string
      - description: user_id
        in: query
        name: user_id
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 提交列表
      tags:
      - 公共方法
  /Login:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        type: string
      - description: password
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 登录
      tags:
      - 公共方法
swagger: "2.0"
